# This is a basic workflow to help you get started with Actions

name: MyFirstWorkflow
on: 
  - push
  - workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  WhatTriggeredTheWorkflow:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
      - run: echo Triggered by ${{ github.event }} 
      - run: echo $EVENT_CONTEXT
  NameOfBranch:
    runs-on: ubuntu-latest
    steps:
     - run: echo The tags are ${{ inputs.tags }} 
  ListOfRepo:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hello world"
