name: MyFirstWorkflow
on: 
  - push
  - workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-context:
    name: Print Context
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
#      - run: echo Triggered by ${{ github.event }} 
        run: |
#          echo $EVENT_CONTEXT
#  b:
#    runs-on: ubuntu-latest
#    steps:
#     - run: echo The tags are ${{ inputs.tags }} 
  c:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world"
