# This is a basic workflow to help you get started with Actions

name: MyFirstWorkflow
on: 
  - push
  - workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - run: mkdir myfolder
      - run: ls


